[package]
name = "lint"
version = "0.1.0"
authors = ["authors go here"]
description = "description goes here"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
#clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "f4850f7292efa33759b4f7f9b7621268979e9914" }
dylint_linting = "2.1.1"
#if_chain = "1.0.2"

#[dev-dependencies]
#dylint_testing = "2.1.1"

#[package.metadata.rust-analyzer]
#rustc_private = true
